const { app, BrowserWindow, Tray, Menu, nativeImage } = require('electron');
const path = require('path');
const fs = require('fs');
const os = require('os');
const http = require('http');

const isDev = !app.isPackaged;

let tray = null;

function getBinaryPath() {
  const ext = process.platform === 'win32' ? '.exe' : '';
  if (isDev) {
    return path.join(__dirname, '..', '..', '..', '..', 'acs', 'target', 'release', `agentcronsystem${ext}`);
  }
  return path.join(process.resourcesPath, 'agentcronsystem-binary', `agentcronsystem${ext}`);
}

function getDataDir() {
  if (process.platform === 'win32') {
    return path.join(
      process.env.LOCALAPPDATA || path.join(os.homedir(), 'AppData', 'Local'),
      'agent-cron-scheduler'
    );
  } else if (process.platform === 'darwin') {
    return path.join(os.homedir(), 'Library', 'Application Support', 'agent-cron-scheduler');
  } else {
    return path.join(
      process.env.XDG_DATA_HOME || path.join(os.homedir(), '.local', 'share'),
      'agent-cron-scheduler'
    );
  }
}

function ensureDataDir() {
  const dataDir = getDataDir();
  fs.mkdirSync(dataDir, { recursive: true });
}

function isDaemonRunning() {
  return new Promise((resolve) => {
    const req = http.get('http://127.0.0.1:8377/health', { timeout: 2000 }, (res) => {
      resolve(res.statusCode === 200);
    });
    req.on('error', () => resolve(false));
    req.on('timeout', () => {
      req.destroy();
      resolve(false);
    });
  });
}

/**
 * Try to resolve a dynamic Next.js route by replacing path segments with "_".
 * Next.js static export with generateStaticParams returning [{ id: "_" }]
 * produces files like: jobs/_.html, jobs/_/edit.html, jobs/_/runs/_.html
 *
 * For a request like /jobs/some-uuid/runs/some-run-id, this function tries
 * progressively replacing segments (right-to-left) with "_" until a matching
 * .html file is found.
 *
 * Returns the resolved file path if found, or null.
 */
function tryDynamicRoute(outDir, segments) {
  // Generate all combinations of replacing segments with "_",
  // prioritizing replacing more segments (rightmost first).
  // Use a bitmask: 1 = replace with "_", 0 = keep original.
  // Skip the all-zeros case (that's the exact match already tried).
  const n = segments.length;
  // Try from most replacements to fewest for best match
  for (let mask = 1; mask < (1 << n); mask++) {
    const candidate = segments.map((seg, i) => (mask & (1 << i)) ? '_' : seg);
    const candidatePath = candidate.join('/');

    // Try candidate.html
    const htmlPath = path.join(outDir, candidatePath + '.html');
    if (fs.existsSync(htmlPath)) return htmlPath;

    // Try candidate/index.html
    const indexPath = path.join(outDir, candidatePath, 'index.html');
    if (fs.existsSync(indexPath)) return indexPath;
  }
  return null;
}

function startStaticServer(outDir) {
  return new Promise((resolve) => {
    const mimeTypes = {
      '.html': 'text/html',
      '.js': 'text/javascript',
      '.css': 'text/css',
      '.json': 'application/json',
      '.png': 'image/png',
      '.jpg': 'image/jpeg',
      '.gif': 'image/gif',
      '.svg': 'image/svg+xml',
      '.ico': 'image/x-icon',
      '.woff': 'font/woff',
      '.woff2': 'font/woff2',
      '.ttf': 'font/ttf',
      '.txt': 'text/plain',
    };

    const server = http.createServer((req, res) => {
      let pathname = decodeURIComponent(new URL(req.url, 'http://localhost').pathname);
      if (pathname.startsWith('/')) pathname = pathname.substring(1);

      let filePath = path.join(outDir, pathname);
      const ext = path.extname(filePath);

      // If has extension, serve directly
      if (ext && fs.existsSync(filePath)) {
        const contentType = mimeTypes[ext] || 'application/octet-stream';
        const content = fs.readFileSync(filePath);
        res.writeHead(200, { 'Content-Type': contentType });
        res.end(content);
        return;
      }

      // SPA fallback for routes without extensions
      // Try {path}.html
      if (fs.existsSync(filePath + '.html')) {
        const content = fs.readFileSync(filePath + '.html');
        res.writeHead(200, { 'Content-Type': 'text/html' });
        res.end(content);
        return;
      }
      // Try {path}/index.html
      if (fs.existsSync(path.join(filePath, 'index.html'))) {
        const content = fs.readFileSync(path.join(filePath, 'index.html'));
        res.writeHead(200, { 'Content-Type': 'text/html' });
        res.end(content);
        return;
      }

      // Dynamic route fallback: replace path segments with "_" placeholder
      // (generated by Next.js static export via generateStaticParams returning [{ id: "_" }])
      // Try replacing segments right-to-left until a matching HTML file is found.
      const segments = pathname.replace(/^\//, '').split('/');
      const resolved = tryDynamicRoute(outDir, segments);
      if (resolved) {
        const content = fs.readFileSync(resolved);
        res.writeHead(200, { 'Content-Type': 'text/html' });
        res.end(content);
        return;
      }

      // Fallback to index.html (SPA)
      const indexPath = path.join(outDir, 'index.html');
      if (fs.existsSync(indexPath)) {
        const content = fs.readFileSync(indexPath);
        res.writeHead(200, { 'Content-Type': 'text/html' });
        res.end(content);
        return;
      }

      res.writeHead(404);
      res.end('Not Found');
    });

    // Listen on random available port
    server.listen(0, '127.0.0.1', () => {
      const port = server.address().port;
      console.log(`Static server running on http://127.0.0.1:${port}`);
      resolve(port);
    });
  });
}

async function startDaemon() {
  const running = await isDaemonRunning();
  if (running) {
    console.log('ACS daemon already running.');
    return;
  }

  const binaryPath = getBinaryPath();
  if (!fs.existsSync(binaryPath)) {
    console.log('ACS binary not found; skipping daemon start');
    return;
  }

  const { spawn } = require('child_process');
  const child = spawn(binaryPath, ['start'], {
    detached: true,
    windowsHide: true,
    stdio: 'ignore',
  });
  child.unref();
  console.log('ACS daemon process launched.');
}

function getTrayIconPath() {
  // Try favicon from built frontend (production)
  const outIcon = path.join(__dirname, '..', 'out', 'favicon.ico');
  if (fs.existsSync(outIcon)) return outIcon;

  // Try from frontend source (dev mode)
  const srcIcon = path.join(__dirname, '..', '..', 'frontend', 'src', 'app', 'favicon.ico');
  if (fs.existsSync(srcIcon)) return srcIcon;

  // No icon found
  return null;
}

function createTray(win) {
  const iconPath = getTrayIconPath();
  if (!iconPath) {
    console.log('No tray icon found; skipping tray creation.');
    return;
  }

  tray = new Tray(iconPath);

  const contextMenu = Menu.buildFromTemplate([
    {
      label: 'Open ACS',
      click: () => { win.show(); win.focus(); }
    },
    { type: 'separator' },
    {
      label: 'Quit',
      click: () => {
        app.isQuitting = true;
        app.quit();
      }
    }
  ]);

  tray.setToolTip('Agent Cron Scheduler');
  tray.setContextMenu(contextMenu);

  // Double-click tray icon to restore window
  tray.on('double-click', () => {
    win.show();
    win.focus();
  });
}

function createWindow(url) {
  const win = new BrowserWindow({
    width: 1200,
    height: 800,
    autoHideMenuBar: true,
    webPreferences: {
      preload: path.join(__dirname, 'preload.js'),
      nodeIntegration: false,
      contextIsolation: true,
      sandbox: false,
      additionalArguments: [
        `--data-dir=${getDataDir()}`,
        `--agentcronsystem-binary=${getBinaryPath()}`,
      ],
    },
  });

  win.setMenuBarVisibility(false);

  // Minimize to tray instead of closing
  win.on('close', (event) => {
    if (!app.isQuitting) {
      event.preventDefault();
      win.hide();
    }
  });

  win.loadURL(url);
  return win;
}

app.whenReady().then(async () => {
  ensureDataDir();
  await startDaemon();

  // Determine frontend URL
  let frontendUrl;
  if (isDev) {
    frontendUrl = 'http://localhost:3000';
  } else {
    // Serve static files via local HTTP server instead of a custom protocol.
    // Custom protocols like app:// break Next.js router internals because
    // Chromium doesn't treat them as valid URL origins for the URL constructor.
    const outDir = path.join(__dirname, '..', 'out');
    const staticPort = await startStaticServer(outDir);
    frontendUrl = `http://127.0.0.1:${staticPort}`;
  }

  const win = createWindow(frontendUrl);
  createTray(win);

  app.on('activate', () => {
    const allWindows = BrowserWindow.getAllWindows();
    if (allWindows.length === 0) {
      const newWin = createWindow(frontendUrl);
      createTray(newWin);
    } else {
      allWindows[0].show();
      allWindows[0].focus();
    }
  });
});

app.on('window-all-closed', () => {
  // Don't quit — app lives in system tray
});

app.on('before-quit', () => {
  app.isQuitting = true;
});
